name: Console Log

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: echo "trial 01"
