name: Pull Request Target

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: echo "Trial 02"
