name: Test Job

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  checkout-and-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' }}

      - name: Checkout pull request
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: List files in the repository
        run: ls -R
